export interface OperationGuide {
  slug: string;
  title: string;
  shortTitle: string;
  metaDescription: string;
  image: string;
  imageAlt: string;
  summary: string;
  sections: Array<{ title: string; paragraphs: string[] }>;
  checks: string[];
  related: Array<{ href: string; label: string; why: string }>;
}

export const OPERATION_GUIDES: OperationGuide[] = [
  {
    slug: "daily-inspection-maintenance",
    title: "Daily forestry attachment inspection and maintenance guide",
    shortTitle: "Daily inspection and maintenance",
    metaDescription: "A practical daily inspection routine for forestry attachments covering structure, pins, hoses, wear parts, rotors, controls, cleaning and records.",
    image: "/images/field/wear-parts-workbench.webp",
    imageAlt: "Forestry attachment service parts and tools prepared on a maintenance workbench",
    summary: "Inspect from the load path outward before the first cycle, then repeat a focused check after warm-up and at shutdown. Clean enough to see cracks and leaks, measure wear against limits, and record changes before a small defect becomes a stopped machine. Give every defect a clear status: safe to monitor, repair before the next shift, or isolate immediately. Record the person responsible and the follow-up date so a verbal observation cannot disappear between crews. Trend repeated findings by attachment hours and work type so planned maintenance responds before the same defect becomes a recurring stoppage. Photograph developing conditions from the same angle and include a scale so the next inspection can identify genuine movement rather than relying on memory.",
    sections: [
      { title: "Begin with isolation and the load path", paragraphs: ["Park on stable ground, lower the attachment into its approved resting position, release stored hydraulic pressure and apply the carrier isolation procedure. Do not inspect beneath a suspended head or rely on the hydraulic system to hold it. Confirm the stand or ground position cannot roll, close or rotate unexpectedly.", "Start at the hitch and bracket, then follow pins, bosses, frame transitions, rotator or headstock and the main attachment body. Look for movement, missing retainers, fretting, elongated holes, cracked paint, distortion and fresh metal. A clean witness mark around a pin or weld often appears before a visible structural crack."] },
      { title: "Inspect hydraulics through the full hose sweep", paragraphs: ["Check couplers, hose covers, crimps, clamps, valve blocks, cylinders and motors for leakage, abrasion, crushing and heat damage. Move the boom and attachment slowly through its normal range while an observer remains in a safe position. A hose that clears at rest may stretch across an edge during tilt or rotation.", "Treat mist, pinhole leakage and a blistered cover as stop-and-repair conditions. Never use a hand to find a hydraulic leak. Clean and cap disconnected couplers, verify the case drain is connected where required, and compare any repeated seal leakage with the commissioning return- or drain-pressure baseline."] },
      { title: "Measure the cutting and wear system", paragraphs: ["Count missing or damaged teeth, blades, chains, holders and fasteners. Measure remaining dimension or clearance where the manufacturer provides a limit, and rotate or replace parts as a complete balanced set when required. Uneven wear is information: it can indicate ground contact, incorrect attack angle, blocked movement or an operator working one side of the head.", "For rotating equipment, check guards, curtains, bearings, belt or drive condition and signs of imbalance. Clear wrapped material only after isolation. A new vibration, sound or temperature change should be investigated before continuing; high-speed rotors convert small loose components into serious projectiles and secondary damage."] },
      { title: "Use warm-up and shutdown as diagnostic checks", paragraphs: ["Run functions at low speed after the cold inspection and listen for abnormal noise, delayed movement or unstable control. After the first loaded cycles, stop safely and check for fresh leakage, hot bearings, hose movement and loosening. This warm check catches faults that do not appear while the system is static.", "At shutdown, clean the attachment for inspection, note wear consumption and record productive hours, faults and parts used. Replenish the field kit at its reorder point. A short written record lets the next operator distinguish a developing pattern from a one-off observation and gives maintenance staff the information needed to plan rather than react."] },
    ],
    checks: ["Attachment safely supported", "Hitch and pin retention", "Frame and weld transitions", "Hose sweep and couplers", "Case drain connected", "Wear parts measured", "Guards and fasteners", "Warm leak and heat check", "Hours and defects recorded", "Field kit replenished"],
    related: [{ href: "/wear-parts/", label: "Wear-parts guide", why: "Turn inspection findings into replacement planning." }, { href: "/troubleshooting/", label: "Troubleshooting", why: "Diagnose heat, vibration and lost performance." }, { href: "/tutorials/build-forestry-attachment-wear-parts-kit/", label: "Build a field kit", why: "Carry the parts that protect the next work period." }],
  },
  {
    slug: "australian-hardwood-operating-guide",
    title: "Operating forestry attachments in Australian hardwood",
    shortTitle: "Australian hardwood operating guide",
    metaDescription: "Operate forestry attachments in dense Australian hardwood by derating capacity, controlling grip and feed, monitoring heat, wear and fibre behaviour.",
    image: "/images/field/tree-shear-field.webp",
    imageAlt: "Tree shear handling dense eucalyptus timber in Australian woodland",
    summary: "Treat published maximums as favourable-material limits. Dense, fibrous, buttressed or dry hardwood can increase cutting force, retained mass, heat and wear at the same visible diameter. Sample representative material, begin below the maximum and build an operating envelope from measured results. Keep species, moisture, stem form and section length with the production record. Diameter alone cannot explain why cycle time, carrier stability or consumable use changed between sites. Preserve representative photographs and measured sections so later operators can recognise the material class behind each limit and production rate.",
    sections: [
      { title: "Diameter is not a complete material specification", paragraphs: ["Species, density, moisture, fibre direction, buttress, branching, decay and growth stress change how a stem cuts and how much it weighs. A smooth plantation stem and an irregular dry eucalyptus trunk with the same measured diameter do not impose the same blade, saw, grip or carrier load.", "Record representative diameter range and form rather than the largest photograph on site. Where timber is retained after cutting, estimate section mass using conservative density and include length. The carrier must hold and place the actual section at radius, not merely support the attachment before the cut."] },
      { title: "Control feed instead of forcing the tool", paragraphs: ["Allow saw, blade, tooth or rotor speed to do the work at the intended hydraulic setting. Excessive feed can stall a motor, deflect a saw bar, spread a shear jaw or turn a mulcher tooth into a lever against the holder. If production drops, inspect sharpness, grip, pressure, return restriction and technique before increasing a machine setting.", "Approach irregular stems so the cutting system engages predictable material and the grip remains stable through separation. Avoid using the attachment as a pry bar outside its designed load path. Repositioning the carrier or taking a smaller section often costs less than repairing jaw alignment, bracket cracks or rotator damage."] },
      { title: "Watch heat and wear as production variables", paragraphs: ["Hard material increases time under pressure and reduces cooling recovery between cycles. Monitor hydraulic temperature, engine load, return pressure and the change in cycle time across the shift. A system that performs for ten minutes may still exceed its thermal envelope during continuous summer work.", "Inspect edges, teeth, chains, holders and fasteners more often while establishing the method. Track parts per productive hour or completed unit by species and ground condition. That record is more useful than a single universal wear allowance and lets estimators price hardwood, dry material and contaminated sites separately."] },
      { title: "Set documented limits operators can recognise", paragraphs: ["Translate engineering limits into field controls: maximum normal diameter by material class, maximum section length at reach bands, prohibited grip positions, temperature stop points and conditions that require a different method. Put the limits with the carrier rather than relying on one experienced operator’s memory.", "Review the envelope after representative work and whenever the head, carrier, coupler, rotator or counterweight changes. Keep an exception method for buttressed, leaning, decayed or oversize trees. Production pressure is least dangerous when the crew already knows which machine or manual method takes over outside the repeatable envelope."] },
    ],
    checks: ["Species and moisture", "Diameter and buttress", "Conservative density", "Section mass at radius", "Sharp cutting system", "Normal feed technique", "Hydraulic temperature", "Wear per productive hour", "Recognisable operator limits", "Exception method"],
    related: [{ href: "/tree-shears-guide/", label: "Tree shear guide", why: "Match grip, cut and carrier to the stem." }, { href: "/grapple-saw-guide/", label: "Grapple saw guide", why: "Control section mass and reach through the cut." }, { href: "/tutorials/size-forestry-attachment-to-excavator/", label: "Size the attachment", why: "Build retained material into the lift assessment." }],
  },
  {
    slug: "transport-storage-changeover",
    title: "Forestry attachment transport, storage and changeover guide",
    shortTitle: "Transport, storage and changeover",
    metaDescription: "Plan forestry attachment transport, stands, lifting, hose protection, contamination control and safe excavator changeovers between work fronts.",
    image: "/images/field/hire-vs-buy-fleet.webp",
    imageAlt: "Excavators and forestry attachments arranged for transport and fleet deployment",
    summary: "Design the attachment as a transportable system: approved resting stand, rated lifting and restraint points, protected hoses and couplers, documented mass and dimensions, and a repeatable changeover sequence. Mobilisation is part of production, not time outside the job. Time the normal crew through loading, connection, testing, disconnection and storage during commissioning. That result belongs in the estimate and reveals where a stand, label, hose park or lifting aid will return its cost. Review the method after any carrier, hitch, rotator, hose or transport change because the safe sequence and dimensions may no longer match.",
    sections: [
      { title: "Decide how the attachment travels before purchase", paragraphs: ["Calculate carrier and attachment mass and dimensions in the actual transport configuration, including hitch, bracket, rotator, guards, counterweight and any transport stand. Confirm whether the head can remain fitted without exceeding float, axle, height, width or restraint limits and whether it blocks safe loading visibility.", "If the attachment travels separately, define the lifting device, rated points, orientation, restraints and unloading surface. Do not assume an irregular head can be placed loose on a deck. The stand should support it against rolling, jaw movement or rotor contact and permit connection without a person entering a crush zone."] },
      { title: "Protect hydraulics from damage and contamination", paragraphs: ["Provide parking points for hoses, caps and plugs for every coupler and a method that keeps lines off the ground. Label supply, return, drain and control connections durably. Hose ends damaged during transport create both a leak risk and contamination path into the carrier and attachment circuits.", "Depressurise using the manufacturer’s method before disconnection and account for temperature-related trapped pressure. Clean couplers before connection and keep spill containment available. Repeated field changes make contamination control a reliability issue; one dirty connection can cost more than the time saved by rushing the sequence."] },
      { title: "Write and time the changeover method", paragraphs: ["List the safe position, isolation, pressure release, electrical disconnection, hose order, hitch sequence, lifting or stand requirements and final functional test. Perform the method with the normal crew during commissioning and record realistic time. Include the same steps for removing the attachment, not only installing it.", "Identify tasks requiring a second person and keep them outside suspended-load and articulation zones. Verify hitch locking visually and functionally. After connection, check hose sweep at low speed and confirm control direction before applying load. A familiar attachment is still a changed machine after every connection."] },
      { title: "Store for the next start, not the last finish", paragraphs: ["Clean enough to inspect, repair known defects, lubricate as specified, protect exposed metal and store the head on a stable stand with hoses capped. Release spring or hydraulic loads only as directed by the manufacturer. Keep controllers, manuals and specialised tools dry, secure and identified with the attachment.", "Record location, condition, hours, wear state and outstanding work. Set a pre-deployment date early enough to obtain parts before the next project. Long idle periods can create corrosion, seal, hose and battery issues even when the previous shift ended normally, so storage does not replace the next pre-start inspection."] },
    ],
    checks: ["Actual transport mass", "Height and width", "Rated restraint points", "Stable storage stand", "Rated lifting method", "Hoses capped and supported", "Connections labelled", "Changeover sequence", "Low-speed function test", "Stored condition recorded"],
    related: [{ href: "/costs/", label: "Ownership costs", why: "Include stands, transport and changeover in the delivered system." }, { href: "/tutorials/install-commission-forestry-attachment/", label: "Commissioning tutorial", why: "Prove the changeover and transport method at delivery." }, { href: "/hire-vs-buy/", label: "Hire or buy", why: "Account for mobilisation across realistic annual use." }],
  },
];

export function operationGuide(slug: string): OperationGuide | undefined { return OPERATION_GUIDES.find((item) => item.slug === slug); }
