import Image from "next/image";
import Link from "next/link";
import { JsonLd } from "@/components/JsonLd";
import { PageHero } from "@/components/PageHero";
import type { PracticalComparison } from "@/lib/practical-comparisons";
import { PRACTICAL_COMPARISONS } from "@/lib/practical-comparisons";
import { absoluteUrl, SITE } from "@/lib/site";

export function PracticalComparisonPage({ comparison }: { comparison: PracticalComparison }) {
  const url = absoluteUrl(`/compare/${comparison.slug}/`);
  return (
    <>
      <PageHero eyebrow="Method comparison" title={comparison.title} crumb={comparison.title} trail={[{ label: "Comparisons", href: "/compare/" }]} lead={comparison.question} />
      <article className="mx-auto max-w-[88rem] px-4 py-16 sm:px-6 sm:py-24 lg:px-10">
        <section className="border-l-[3px] border-hazard bg-steel-900 p-6 sm:p-9"><p className="font-mono text-[0.62rem] tracking-[0.2em] text-hazard uppercase">The short answer</p><p className="mt-4 max-w-4xl text-lg leading-relaxed text-bone sm:text-xl">{comparison.verdict}</p></section>
        <div className="mt-12 grid gap-px bg-steel-700 md:grid-cols-2">{[comparison.a, comparison.b].map((side, index) => <section key={side.name} className="bg-steel-900"><div className="relative aspect-[16/9] overflow-hidden"><Image src={side.image} alt={side.alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="field-image object-cover" /></div><div className="p-7"><span className="font-mono text-[0.68rem] text-hazard">{index === 0 ? "A" : "B"}</span><h2 className="display mt-3 text-3xl text-bone">{side.name}</h2><p className="mt-4 text-[1rem] leading-relaxed text-concrete">{side.role}</p></div></section>)}</div>
        <section className="mt-16"><div className="rule-heavy" /><h2 className="display mt-5 text-3xl text-bone sm:text-4xl">Side by side</h2><div className="mt-8 overflow-x-auto border border-steel-700" tabIndex={0} role="region" aria-label="Scrollable comparison table"><table className="w-full min-w-[44rem] border-collapse text-sm"><thead><tr>{["Criterion", comparison.a.name, comparison.b.name].map((heading) => <th key={heading} className="border-l border-steel-700 bg-steel-800 px-4 py-4 text-left font-mono text-[0.62rem] tracking-[0.14em] text-hazard uppercase first:border-l-0">{heading}</th>)}</tr></thead><tbody>{comparison.rows.map((row) => <tr key={row.criterion} className="border-t border-steel-700"><th scope="row" className="bg-steel-900 px-4 py-4 text-left text-bone">{row.criterion}</th><td className="border-l border-steel-700 bg-steel-900 px-4 py-4 text-concrete">{row.a}</td><td className="border-l border-steel-700 bg-steel-900 px-4 py-4 text-concrete">{row.b}</td></tr>)}</tbody></table></div></section>
        <div className="mt-16 space-y-14">{comparison.sections.map((section) => <section key={section.title}><div className="rule-heavy" /><h2 className="display mt-5 text-3xl text-bone sm:text-4xl">{section.title}</h2><div className="mt-6 max-w-3xl space-y-5 text-[1rem] leading-relaxed text-concrete">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}</div>
        <section className="mt-16"><div className="rule-heavy" /><h2 className="display mt-5 text-3xl text-bone sm:text-4xl">Run a matched field trial before committing</h2><div className="mt-6 max-w-3xl space-y-5 text-[1rem] leading-relaxed text-concrete"><p>Choose a representative work area for each method and define the same accepted endpoint before the clock starts. Record mobilisation, setup, productive work, repositioning, supporting crew and plant, consumables, fuel, delays, material handling, clean-up and inspection. Include every paid hour until the site or work front is released. A trial that stops when the cutting action finishes measures a mechanism rather than a service.</p><p>Document material size and density, terrain, access, weather, contamination and operator experience so the result can be reused honestly. Compare completed units per crew shift and total cost per accepted unit, then test the result against low and high production cases. Keep safety controls and exposure changes visible beside the cost: a method may justify itself through fewer people in a drop zone, a smaller exclusion period or less rehandling even when its direct hourly rate is higher.</p><p>Use the trial to set operating assumptions, not to declare a permanent winner. Different work packages can reverse the result. Retain a clear boundary for conditions that require the other method and price those exceptions rather than forcing one system across every site.</p></div></section>
        <section className="mt-16"><div className="rule-heavy" /><h2 className="display mt-5 text-3xl text-bone">How this choice goes wrong</h2><div className="mt-8 grid gap-px bg-steel-700 sm:grid-cols-2">{comparison.mistakes.map((item) => <div key={item.title} className="bg-steel-900 p-6"><h3 className="display text-xl text-bone">{item.title}</h3><p className="mt-3 text-[0.94rem] leading-relaxed text-concrete">{item.body}</p></div>)}</div></section>
        <section className="mt-16 grid gap-10 lg:grid-cols-[22rem_minmax(0,1fr)]"><div className="border border-steel-700 bg-steel-900 p-6"><p className="font-mono text-[0.62rem] tracking-[0.18em] text-hazard uppercase">Decision record</p><ul className="mt-5 space-y-3">{comparison.checklist.map((item) => <li key={item} className="flex gap-3 text-sm text-bone/85"><span className="h-3.5 w-3.5 shrink-0 border border-hazard" />{item}</li>)}</ul></div><div><p className="eyebrow">Continue the decision</p><div className="mt-5 grid gap-px bg-steel-700 sm:grid-cols-3">{comparison.related.map((item) => <div key={item.href} className="group relative bg-steel-900 p-6"><h3 className="display text-xl text-bone group-hover:text-hazard"><Link href={item.href} className="after:absolute after:inset-0">{item.label}</Link></h3><p className="mt-3 text-sm leading-relaxed text-concrete">{item.why}</p></div>)}</div></div></section>
        <section aria-label="Other practical comparisons" className="mt-16 border-t border-steel-700 pt-8"><p className="font-mono text-[0.65rem] tracking-[0.18em] text-concrete uppercase">More comparisons</p><div className="mt-5 flex flex-wrap gap-3">{PRACTICAL_COMPARISONS.filter((item) => item.slug !== comparison.slug).map((item) => <Link key={item.slug} href={`/compare/${item.slug}/`} className="border border-steel-600 px-4 py-2.5 text-sm text-bone/85 hover:border-hazard hover:text-hazard">{item.title} →</Link>)}</div></section>
      </article>
      <JsonLd data={{ "@context": "https://schema.org", "@type": "Article", headline: comparison.title, description: comparison.metaDescription, url, mainEntityOfPage: url, author: { "@type": "Organization", name: SITE.name }, publisher: { "@type": "Organization", name: SITE.name }, dateModified: "2026-09-19", inLanguage: "en-AU" }} />
      <JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: absoluteUrl("/") }, { "@type": "ListItem", position: 2, name: "Comparisons", item: absoluteUrl("/compare/") }, { "@type": "ListItem", position: 3, name: comparison.title, item: url }] }} />
    </>
  );
}
